[package]
name = "rust"
version = "0.1.0"
authors = ["Fallstop <jasper@ngita.co.nz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
regex = "1.3.4"