name: rust-bf
version: 2.1.0
summary: A super fast brainfuck interpreter written in rust
description: |
  rust-bf is a command line program for running 64 bit
  brainfuck programs at super speed. Use the --help tag to
  find out more.

base: core18
confinement: strict

parts:
  rust-bf:
    plugin: rust
    source: .

apps:
  rust-bf:
    command: bin/rust-bf
    plugs: 
        - home
