name: rust-bf
version: 2.2.0
summary: A super fast brainfuck interpreter written in rust
description: |
  rust-bf is a command line program for running 128 bit
  brainfuck programs at a speed that requires 128 bits.
  Use the --help tag to find out more.

base: core18
confinement: strict

parts:
  rust-bf:
    plugin: rust
    source: .

apps:
  rust-bf:
    command: bin/rust-bf
    plugs: 
        - home
