name: bf-haskell
version: 0.1.0.0
github: "fallstop/bf-in-rosetta/bf-haskell"
license: MIT
author: "Nathan Hare"
maintainer: "example@example.com"
copyright: "2021 Nathan Hare"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/bf-haskell#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  bf-haskell-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - bf-haskell
